[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "holigram"
version = "0.1.0"
description = "App de slas"
authors = ["Jeremias Olivera <jeremiasolivera14@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.2.6"
pillow = "^9.5.0"
django-environ = "^0.10.0"
gunicorn = "^20.1.0"
whitenoise = "^5.2.0"
django-allauth = "^0.54.0"
sqlparse = "^0.4.4"
pytz = "^2023.3"
asgiref = "^3.6.0"
python3-openid = "^3.2.0"
requests-oauthlib = "^1.3.1"
requests = "^2.30.0"
pyjwt = "^2.7.0"
typing-extensions = "^4.5.0"
defusedxml = "^0.7.1"
oauthlib = "^3.2.2"
idna = "^3.4"
urllib3 = "^2.0.2"
certifi = "^2023.5.7"
charset-normalizer = "^3.1.0"
cryptography = {version = "^40.0.2", optional = true}
pyjwt = {version = "^2.7.0", extras = ["crypto"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
